version: "3.5"
services:
  db:
    image: postgres:10.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hangman
      POSTGRES_PASSWORD: hangman
      POSTGRES_DB: hangman

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${ASPNETCORE_SOCKET_BIND_PORT}:${ASPNETCORE_SOCKET_BIND_PORT}"
    depends_on:
      - db
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./start-from-compose.sh",
      ]
