### gets room by id
GET http://localhost:8080/api/v1/gameroom/824558a6-a118-4513-9e83-e81399cfa7a7
Content-Type: application/json

### gets all rooms (default pagination)
GET http://localhost:8080/api/v1/gameroom/
Content-Type: application/json

### gets all rooms (paginated)
GET http://localhost:8080/api/v1/gameroom/
    ?pageSize=2
    &pageNumber=1
    &name=igu room 2
Content-Type: application/json

### creates a new gameroom
POST http://localhost:8080/api/v1/gameroom/
Content-Type: application/json

{
    "name": "igu room 3"
}